// Package winianatz provides support in converting date timezones from
// the non-standard windows timezone format into IANA format.
//
// Originally written by Gary Barnett (2018), released into the Public Domain.
// Modified by Artem Danilov (2025). This modified version is released under
// the MIT License. See LICENSE for details.
package winianatz

import (
	"errors"
	"time"
)

// WinIANA is a pseudo constant that provides a mapping between the Windows timezones and the IANA zones
// Source: https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml
var WinIANA = map[string]string{
	"(UTC-12:00) International Date Line West":                      "Etc/GMT+12",
	"(UTC-11:00) Coordinated Universal Time-11":                     "Etc/GMT+11",
	"(UTC-10:00) Aleutian Islands":                                  "America/Adak",
	"(UTC-10:00) Hawaii":                                            "Pacific/Honolulu",
	"(UTC-09:30) Marquesas Islands":                                 "Pacific/Marquesas",
	"(UTC-09:00) Alaska":                                            "America/Anchorage",
	"(UTC-09:00) Coordinated Universal Time-09":                     "Etc/GMT+9",
	"(UTC-08:00) Baja California":                                   "America/Tijuana",
	"(UTC-08:00) Coordinated Universal Time-08":                     "Etc/GMT+8",
	"(UTC-08:00) Pacific Time (US & Canada)":                        "America/Los_Angeles",
	"(UTC-07:00) Arizona":                                           "America/Phoenix",
	"(UTC-07:00) Chihuahua, La Paz, Mazatlan":                       "America/Mazatlan",
	"(UTC-07:00) Mountain Time (US & Canada)":                       "America/Denver",
	"(UTC-07:00) Yukon":                                             "America/Whitehorse",
	"(UTC-06:00) Central America":                                   "America/Guatemala",
	"(UTC-06:00) Central Time (US & Canada)":                        "America/Chicago",
	"(UTC-06:00) Easter Island":                                     "Pacific/Easter",
	"(UTC-06:00) Guadalajara, Mexico City, Monterrey":               "America/Mexico_City",
	"(UTC-06:00) Saskatchewan":                                      "America/Regina",
	"(UTC-05:00) Bogota, Lima, Quito, Rio Branco":                   "America/Bogota",
	"(UTC-05:00) Chetumal":                                          "America/Cancun",
	"(UTC-05:00) Eastern Time (US & Canada)":                        "America/New_York",
	"(UTC-05:00) Haiti":                                             "America/Port-au-Prince",
	"(UTC-05:00) Havana":                                            "America/Havana",
	"(UTC-05:00) Indiana (East)":                                    "America/Indianapolis",
	"(UTC-05:00) Turks and Caicos":                                  "America/Grand_Turk",
	"(UTC-04:00) Asuncion":                                          "America/Asuncion",
	"(UTC-04:00) Atlantic Time (Canada)":                            "America/Halifax",
	"(UTC-04:00) Caracas":                                           "America/Caracas",
	"(UTC-04:00) Cuiaba":                                            "America/Cuiaba",
	"(UTC-04:00) Georgetown, La Paz, Manaus, San Juan":              "America/La_Paz",
	"(UTC-04:00) Santiago":                                          "America/Santiago",
	"(UTC-03:30) Newfoundland":                                      "America/St_Johns",
	"(UTC-03:00) Araguaina":                                         "America/Araguaina",
	"(UTC-03:00) Brasilia":                                          "America/Sao_Paulo",
	"(UTC-03:00) Cayenne, Fortaleza":                                "America/Cayenne",
	"(UTC-03:00) City of Buenos Aires":                              "America/Buenos_Aires",
	"(UTC-03:00) Greenland":                                         "America/Godthab",
	"(UTC-03:00) Montevideo":                                        "America/Montevideo",
	"(UTC-03:00) Punta Arenas":                                      "America/Punta_Arenas",
	"(UTC-03:00) Saint Pierre and Miquelon":                         "America/Miquelon",
	"(UTC-03:00) Salvador":                                          "America/Bahia",
	"(UTC-02:00) Coordinated Universal Time-02":                     "Etc/GMT+2",
	"(UTC-01:00) Azores":                                            "Atlantic/Azores",
	"(UTC-01:00) Cabo Verde Is.":                                    "Atlantic/Cape_Verde",
	"(UTC) Coordinated Universal Time":                              "Etc/UTC",
	"(UTC+00:00) Dublin, Edinburgh, Lisbon, London":                 "Europe/London",
	"(UTC+00:00) Monrovia, Reykjavik":                               "Atlantic/Reykjavik",
	"(UTC+00:00) Sao Tome":                                          "Africa/Sao_Tome",
	"(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna":  "Europe/Berlin",
	"(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague": "Europe/Budapest",
	"(UTC+01:00) Brussels, Copenhagen, Madrid, Paris":               "Europe/Paris",
	"(UTC+01:00) Casablanca":                                        "Africa/Casablanca",
	"(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb":                  "Europe/Warsaw",
	"(UTC+01:00) West Central Africa":                               "Africa/Lagos",
	"(UTC+02:00) Amman":                                             "Asia/Amman",
	"(UTC+02:00) Athens, Bucharest":                                 "Europe/Bucharest",
	"(UTC+02:00) Beirut":                                            "Asia/Beirut",
	"(UTC+02:00) Cairo":                                             "Africa/Cairo",
	"(UTC+02:00) Chisinau":                                          "Europe/Chisinau",
	"(UTC+02:00) Damascus":                                          "Asia/Damascus",
	"(UTC+02:00) Gaza, Hebron":                                      "Asia/Hebron",
	"(UTC+02:00) Harare, Pretoria":                                  "Africa/Johannesburg",
	"(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":     "Europe/Kiev",
	"(UTC+02:00) Jerusalem":                                         "Asia/Jerusalem",
	"(UTC+02:00) Juba":                                              "Africa/Juba",
	"(UTC+02:00) Kaliningrad":                                       "Europe/Kaliningrad",
	"(UTC+02:00) Khartoum":                                          "Africa/Khartoum",
	"(UTC+02:00) Tripoli":                                           "Africa/Tripoli",
	"(UTC+02:00) Windhoek":                                          "Africa/Windhoek",
	"(UTC+03:00) Baghdad":                                           "Asia/Baghdad",
	"(UTC+03:00) Istanbul":                                          "Europe/Istanbul",
	"(UTC+03:00) Kuwait, Riyadh":                                    "Asia/Riyadh",
	"(UTC+03:00) Minsk":                                             "Europe/Minsk",
	"(UTC+03:00) Moscow, St. Petersburg":                            "Europe/Moscow",
	"(UTC+03:00) Nairobi":                                           "Africa/Nairobi",
	"(UTC+03:30) Tehran":                                            "Asia/Tehran",
	"(UTC+04:00) Abu Dhabi, Muscat":                                 "Asia/Dubai",
	"(UTC+04:00) Astrakhan, Ulyanovsk":                              "Europe/Astrakhan",
	"(UTC+04:00) Baku":                                              "Asia/Baku",
	"(UTC+04:00) Izhevsk, Samara":                                   "Europe/Samara",
	"(UTC+04:00) Port Louis":                                        "Indian/Mauritius",
	"(UTC+04:00) Saratov":                                           "Europe/Saratov",
	"(UTC+04:00) Tbilisi":                                           "Asia/Tbilisi",
	"(UTC+04:00) Volgograd":                                         "Europe/Volgograd",
	"(UTC+04:00) Yerevan":                                           "Asia/Yerevan",
	"(UTC+04:30) Kabul":                                             "Asia/Kabul",
	"(UTC+05:00) Ashgabat, Tashkent":                                "Asia/Tashkent",
	"(UTC+05:00) Ekaterinburg":                                      "Asia/Yekaterinburg",
	"(UTC+05:00) Islamabad, Karachi":                                "Asia/Karachi",
	"(UTC+05:00) Qyzylorda":                                         "Asia/Qyzylorda",
	"(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi":               "Asia/Calcutta",
	"(UTC+05:30) Sri Jayawardenepura":                               "Asia/Colombo",
	"(UTC+05:45) Kathmandu":                                         "Asia/Katmandu",
	"(UTC+06:00) Astana":                                            "Asia/Bishkek",
	"(UTC+06:00) Dhaka":                                             "Asia/Dhaka",
	"(UTC+06:00) Omsk":                                              "Asia/Omsk",
	"(UTC+06:30) Yangon (Rangoon)":                                  "Asia/Rangoon",
	"(UTC+07:00) Bangkok, Hanoi, Jakarta":                           "Asia/Bangkok",
	"(UTC+07:00) Barnaul, Gorno-Altaysk":                            "Asia/Barnaul",
	"(UTC+07:00) Hovd":                                              "Asia/Hovd",
	"(UTC+07:00) Krasnoyarsk":                                       "Asia/Krasnoyarsk",
	"(UTC+07:00) Novosibirsk":                                       "Asia/Novosibirsk",
	"(UTC+07:00) Tomsk":                                             "Asia/Tomsk",
	"(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi":             "Asia/Shanghai",
	"(UTC+08:00) Irkutsk":                                           "Asia/Irkutsk",
	"(UTC+08:00) Kuala Lumpur, Singapore":                           "Asia/Singapore",
	"(UTC+08:00) Perth":                                             "Australia/Perth",
	"(UTC+08:00) Taipei":                                            "Asia/Taipei",
	"(UTC+08:00) Ulaanbaatar":                                       "Asia/Ulaanbaatar",
	"(UTC+08:45) Eucla":                                             "Australia/Eucla",
	"(UTC+09:00) Chita":                                             "Asia/Chita",
	"(UTC+09:00) Osaka, Sapporo, Tokyo":                             "Asia/Tokyo",
	"(UTC+09:00) Pyongyang":                                         "Asia/Pyongyang",
	"(UTC+09:00) Seoul":                                             "Asia/Seoul",
	"(UTC+09:00) Yakutsk":                                           "Asia/Yakutsk",
	"(UTC+09:30) Adelaide":                                          "Australia/Adelaide",
	"(UTC+09:30) Darwin":                                            "Australia/Darwin",
	"(UTC+10:00) Brisbane":                                          "Australia/Brisbane",
	"(UTC+10:00) Canberra, Melbourne, Sydney":                       "Australia/Sydney",
	"(UTC+10:00) Guam, Port Moresby":                                "Pacific/Port_Moresby",
	"(UTC+10:00) Hobart":                                            "Australia/Hobart",
	"(UTC+10:00) Vladivostok":                                       "Asia/Vladivostok",
	"(UTC+10:30) Lord Howe Island":                                  "Australia/Lord_Howe",
	"(UTC+11:00) Bougainville Island":                               "Pacific/Bougainville",
	"(UTC+11:00) Chokurdakh":                                        "Asia/Srednekolymsk",
	"(UTC+11:00) Magadan":                                           "Asia/Magadan",
	"(UTC+11:00) Norfolk Island":                                    "Pacific/Norfolk",
	"(UTC+11:00) Sakhalin":                                          "Asia/Sakhalin",
	"(UTC+11:00) Solomon Is., New Caledonia":                        "Pacific/Guadalcanal",
	"(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky":                  "Asia/Kamchatka",
	"(UTC+12:00) Auckland, Wellington":                              "Pacific/Auckland",
	"(UTC+12:00) Coordinated Universal Time+12":                     "Etc/GMT-12",
	"(UTC+12:00) Fiji":                                              "Pacific/Fiji",
	"(UTC+12:45) Chatham Islands":                                   "Pacific/Chatham",
	"(UTC+13:00) Coordinated Universal Time+13":                     "Etc/GMT-13",
	"(UTC+13:00) Nuku'alofa":                                        "Pacific/Tongatapu",
	"(UTC+13:00) Samoa":                                             "Pacific/Apia",
	"(UTC+14:00) Kiritimati Island":                                 "Pacific/Kiritimati",
}

// MicrosoftIANA is a mapping between Microsoft timezone identifiers and IANA zones
// Source: https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml
var MicrosoftIANA = map[string]string{
	"AUS Central Standard Time":       "Australia/Darwin",
	"AUS Eastern Standard Time":       "Australia/Sydney",
	"Afghanistan Standard Time":       "Asia/Kabul",
	"Alaskan Standard Time":           "America/Anchorage",
	"Aleutian Standard Time":          "America/Adak",
	"Altai Standard Time":             "Asia/Barnaul",
	"Arab Standard Time":              "Asia/Riyadh",
	"Arabian Standard Time":           "Asia/Dubai",
	"Arabic Standard Time":            "Asia/Baghdad",
	"Argentina Standard Time":         "America/Buenos_Aires",
	"Astrakhan Standard Time":         "Europe/Astrakhan",
	"Atlantic Standard Time":          "America/Halifax",
	"Aus Central W. Standard Time":    "Australia/Eucla",
	"Azerbaijan Standard Time":        "Asia/Baku",
	"Azores Standard Time":            "Atlantic/Azores",
	"Bahia Standard Time":             "America/Bahia",
	"Bangladesh Standard Time":        "Asia/Dhaka",
	"Belarus Standard Time":           "Europe/Minsk",
	"Bougainville Standard Time":      "Pacific/Bougainville",
	"Canada Central Standard Time":    "America/Regina",
	"Cape Verde Standard Time":        "Atlantic/Cape_Verde",
	"Caucasus Standard Time":          "Asia/Yerevan",
	"Cen. Australia Standard Time":    "Australia/Adelaide",
	"Central America Standard Time":   "America/Guatemala",
	"Central Asia Standard Time":      "Asia/Bishkek",
	"Central Brazilian Standard Time": "America/Cuiaba",
	"Central Europe Standard Time":    "Europe/Budapest",
	"Central European Standard Time":  "Europe/Warsaw",
	"Central Pacific Standard Time":   "Pacific/Guadalcanal",
	"Central Standard Time":           "America/Chicago",
	"Central Standard Time (Mexico)":  "America/Mexico_City",
	"Chatham Islands Standard Time":   "Pacific/Chatham",
	"China Standard Time":             "Asia/Shanghai",
	"Cuba Standard Time":              "America/Havana",
	"Dateline Standard Time":          "Etc/GMT+12",
	"E. Africa Standard Time":         "Africa/Nairobi",
	"E. Australia Standard Time":      "Australia/Brisbane",
	"E. Europe Standard Time":         "Europe/Chisinau",
	"E. South America Standard Time":  "America/Sao_Paulo",
	"Easter Island Standard Time":     "Pacific/Easter",
	"Eastern Standard Time":           "America/New_York",
	"Eastern Standard Time (Mexico)":  "America/Cancun",
	"Egypt Standard Time":             "Africa/Cairo",
	"Ekaterinburg Standard Time":      "Asia/Yekaterinburg",
	"FLE Standard Time":               "Europe/Kiev",
	"Fiji Standard Time":              "Pacific/Fiji",
	"GMT Standard Time":               "Europe/London",
	"GTB Standard Time":               "Europe/Bucharest",
	"Georgian Standard Time":          "Asia/Tbilisi",
	"Greenland Standard Time":         "America/Godthab",
	"Greenwich Standard Time":         "Atlantic/Reykjavik",
	"Haiti Standard Time":             "America/Port-au-Prince",
	"Hawaiian Standard Time":          "Pacific/Honolulu",
	"India Standard Time":             "Asia/Calcutta",
	"Iran Standard Time":              "Asia/Tehran",
	"Israel Standard Time":            "Asia/Jerusalem",
	"Jordan Standard Time":            "Asia/Amman",
	"Kaliningrad Standard Time":       "Europe/Kaliningrad",
	"Korea Standard Time":             "Asia/Seoul",
	"Libya Standard Time":             "Africa/Tripoli",
	"Line Islands Standard Time":      "Pacific/Kiritimati",
	"Lord Howe Standard Time":         "Australia/Lord_Howe",
	"Magadan Standard Time":           "Asia/Magadan",
	"Magallanes Standard Time":        "America/Punta_Arenas",
	"Marquesas Standard Time":         "Pacific/Marquesas",
	"Mauritius Standard Time":         "Indian/Mauritius",
	"Middle East Standard Time":       "Asia/Beirut",
	"Montevideo Standard Time":        "America/Montevideo",
	"Morocco Standard Time":           "Africa/Casablanca",
	"Mountain Standard Time":          "America/Denver",
	"Mountain Standard Time (Mexico)": "America/Mazatlan",
	"Myanmar Standard Time":           "Asia/Rangoon",
	"N. Central Asia Standard Time":   "Asia/Novosibirsk",
	"Namibia Standard Time":           "Africa/Windhoek",
	"Nepal Standard Time":             "Asia/Katmandu",
	"New Zealand Standard Time":       "Pacific/Auckland",
	"Newfoundland Standard Time":      "America/St_Johns",
	"Norfolk Standard Time":           "Pacific/Norfolk",
	"North Asia East Standard Time":   "Asia/Irkutsk",
	"North Asia Standard Time":        "Asia/Krasnoyarsk",
	"North Korea Standard Time":       "Asia/Pyongyang",
	"Omsk Standard Time":              "Asia/Omsk",
	"Pacific SA Standard Time":        "America/Santiago",
	"Pacific Standard Time":           "America/Los_Angeles",
	"Pacific Standard Time (Mexico)":  "America/Tijuana",
	"Pakistan Standard Time":          "Asia/Karachi",
	"Paraguay Standard Time":          "America/Asuncion",
	"Qyzylorda Standard Time":         "Asia/Qyzylorda",
	"Romance Standard Time":           "Europe/Paris",
	"Russia Time Zone 10":             "Asia/Srednekolymsk",
	"Russia Time Zone 11":             "Asia/Kamchatka",
	"Russia Time Zone 3":              "Europe/Samara",
	"Russian Standard Time":           "Europe/Moscow",
	"SA Eastern Standard Time":        "America/Cayenne",
	"SA Pacific Standard Time":        "America/Bogota",
	"SA Western Standard Time":        "America/La_Paz",
	"SE Asia Standard Time":           "Asia/Bangkok",
	"Saint Pierre Standard Time":      "America/Miquelon",
	"Sakhalin Standard Time":          "Asia/Sakhalin",
	"Samoa Standard Time":             "Pacific/Apia",
	"Sao Tome Standard Time":          "Africa/Sao_Tome",
	"Saratov Standard Time":           "Europe/Saratov",
	"Singapore Standard Time":         "Asia/Singapore",
	"South Africa Standard Time":      "Africa/Johannesburg",
	"South Sudan Standard Time":       "Africa/Juba",
	"Sri Lanka Standard Time":         "Asia/Colombo",
	"Sudan Standard Time":             "Africa/Khartoum",
	"Syria Standard Time":             "Asia/Damascus",
	"Taipei Standard Time":            "Asia/Taipei",
	"Tasmania Standard Time":          "Australia/Hobart",
	"Tocantins Standard Time":         "America/Araguaina",
	"Tokyo Standard Time":             "Asia/Tokyo",
	"Tomsk Standard Time":             "Asia/Tomsk",
	"Tonga Standard Time":             "Pacific/Tongatapu",
	"Transbaikal Standard Time":       "Asia/Chita",
	"Turkey Standard Time":            "Europe/Istanbul",
	"Turks And Caicos Standard Time":  "America/Grand_Turk",
	"US Eastern Standard Time":        "America/Indianapolis",
	"US Mountain Standard Time":       "America/Phoenix",
	"UTC":                             "Etc/UTC",
	"UTC+12":                          "Etc/GMT-12",
	"UTC+13":                          "Etc/GMT-13",
	"UTC-02":                          "Etc/GMT+2",
	"UTC-08":                          "Etc/GMT+8",
	"UTC-09":                          "Etc/GMT+9",
	"UTC-11":                          "Etc/GMT+11",
	"Ulaanbaatar Standard Time":       "Asia/Ulaanbaatar",
	"Venezuela Standard Time":         "America/Caracas",
	"Vladivostok Standard Time":       "Asia/Vladivostok",
	"Volgograd Standard Time":         "Europe/Volgograd",
	"W. Australia Standard Time":      "Australia/Perth",
	"W. Central Africa Standard Time": "Africa/Lagos",
	"W. Europe Standard Time":         "Europe/Berlin",
	"W. Mongolia Standard Time":       "Asia/Hovd",
	"West Asia Standard Time":         "Asia/Tashkent",
	"West Bank Standard Time":         "Asia/Hebron",
	"West Pacific Standard Time":      "Pacific/Port_Moresby",
	"Yakutsk Standard Time":           "Asia/Yakutsk",
	"Yukon Standard Time":             "America/Whitehorse",
}

// TimezoneParseWindows accepts a timestring in the format "2006-01-02T15:04:05" as the tstring
// parameter and a windows time zone (eg "(UTC+12:00) Fiji") as the timezone. It will return
// a timezoned date, which will correctly handle daylight savings time if it's in force at the given date
func TimezoneParseWindows(tstring string, tzone string) (time.Time, error) {
	ianazone := WinIANA[tzone]
	if ianazone == "" {
		var t time.Time
		return t, errors.New("Could not match windows timezone to IANA timezone")
	}
	return TimezoneParseIANA(tstring, WinIANA[tzone])
}

// TimezoneParseIANA accepts a timestring in the format "2006-01-02T15:04:05" as the tstring
// parameter and am IANA time zone (eg  "Pacific/Fiji") as the timezone. It will return
// a timezoned date, which will correctly handle daylight savings time if it's in force at the given date
func TimezoneParseIANA(tstring string, tzone string) (time.Time, error) {
	var zulutime time.Time
	it, err := time.Parse("2006-01-02T15:04:05", tstring)

	if err != nil {
		return zulutime, err
	}
	loc, err := time.LoadLocation(tzone)
	if err != nil {
		return zulutime, err
	}
	zulutime = time.Date(it.Year(), it.Month(), it.Day(), it.Hour(), it.Minute(), it.Second(), 0, loc)
	return zulutime, nil
}

// StripTimezoneFromDate removes the same point in time and date, but strips apart the timezone
func StripTimezoneFromDate(indate time.Time) time.Time {
	return time.Unix(indate.Unix(), 0)
}
