package main

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"go/format"
	"io"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

const (
	xmlFile  = "references/windowsZones.xml"
	goFile   = "data_gen.go"
	jsonFile = "data_gen.json"
)

type SupplementalData struct {
	XMLName      xml.Name     `xml:"supplementalData"`
	WindowsZones WindowsZones `xml:"windowsZones"`
}

type WindowsZones struct {
	MapTimezones MapTimezones `xml:"mapTimezones"`
}

type MapTimezones struct {
	MapZone []MapZone `xml:"mapZone"`
}

type MapZone struct {
	Other     string `xml:"other,attr"`
	Territory string `xml:"territory,attr"`
	Type      string `xml:"type,attr"`
	Comment   string `xml:",comment"`
}

type XMLNode struct {
	XMLName  xml.Name
	Content  string    `xml:",chardata"`
	Comment  string    `xml:",comment"`
	Children []XMLNode `xml:",any"`
}

// Entry represents a timezone mapping between Microsoft Windows timezone identifiers and IANA timezone names.
type Entry struct {
	// Alias is the Microsoft Windows timezone identifier (e.g., "Hawaiian Standard Time").
	Alias string `json:"microsoftAlias"`
	// Display is the human-readable timezone display name used by Microsoft (e.g., "(UTC-10:00) Hawaii").
	Display string `json:"microsoftDisplayName"`
	// Territory is the ISO 3166 territory code where this mapping applies (e.g., "001" for global, "US" for United States).
	Territory string `json:"territory"`
	// IANA is the standard IANA timezone identifier (e.g., "Pacific/Honolulu").
	IANA string `json:"iana"`
}

// SupportedTZID represents a supported IANA timezone identifier.
type SupportedTZID struct {
	// IANA is the standard IANA timezone identifier (e.g., "Pacific/Honolulu").
	IANA string `json:"iana"`
}

const fileTemplate = `// This file is automatically generated by the generator
// DO NOT EDIT MANUALLY
package winianatz

var data = []Entry{
{{range .Entries}}	{MicrosoftAlias: "{{.Alias}}", MicrosoftDisplayName: "{{.Display}}", Territory: "{{.Territory}}", IANA: "{{.IANA}}"},
{{end}}}

var supportedTZIDs = []SupportedTZID{
{{range .SupportedTZIDs}}	{IANA: "{{.IANA}}"},
{{end}}}
`

func main() {
	log.Println("Parsing XML...")
	entries, err := parseXML(xmlFile)
	if err != nil {
		log.Fatalf("Failed to parse XML: %v", err)
	}

	log.Println("Processing and sorting data...")
	sortedEntries := processAndSortEntries(entries)

	log.Println("Generating data_gen.go...")
	if err := generateGoFile(sortedEntries); err != nil {
		log.Fatalf("Failed to generate Go file: %v", err)
	}

	log.Println("Generating data_gen.json...")
	if err := generateJSONFile(sortedEntries); err != nil {
		log.Fatalf("Failed to generate JSON file: %v", err)
	}

	log.Println("Successfully generated data_gen.go and data_gen.json")
}

// parseXML parses the CLDR windowsZones.xml file and extracts timezone mapping entries.
// It returns a slice of Entry structs containing the timezone mappings.
func parseXML(filepath string) ([]Entry, error) {
	data, err := os.ReadFile(filepath)
	if err != nil {
		return nil, err
	}

	var entries []Entry
	decoder := xml.NewDecoder(bytes.NewReader(data))
	var currentComment string

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}

		switch t := token.(type) {
		case xml.Comment:
			comment := strings.TrimSpace(string(t))
			if strings.HasPrefix(comment, "(UTC") {
				currentComment = comment
			}
		case xml.StartElement:
			if t.Name.Local == "mapZone" {
				var mapZone MapZone
				if err := decoder.DecodeElement(&mapZone, &t); err != nil {
					return nil, err
				}

				// Process all territory entries with the current comment
				if currentComment != "" {
					// Handle multiple IANA zones separated by spaces
					ianaZones := strings.Fields(mapZone.Type)

					// Create an entry for each IANA zone
					for _, ianaZone := range ianaZones {
						entry := Entry{
							Alias:     mapZone.Other,
							Display:   currentComment,
							IANA:      ianaZone,
							Territory: mapZone.Territory,
						}
						entries = append(entries, entry)
					}
				}
			}
		}
	}

	return entries, nil
}

// processAndSortEntries processes the raw entries and sorts them by UTC offset, display name, and territory.
// This ensures a consistent ordering in the generated output files.
func processAndSortEntries(entries []Entry) []Entry {
	// Helper to extract offset as minutes from display string using regexp
	re := regexp.MustCompile(`\(UTC([+-]\d{2}:\d{2})\)`)
	parseOffset := func(display string) int {
		// Handle exactly "(UTC) ..." as offset 0
		if strings.HasPrefix(display, "(UTC)") {
			return 0
		}
		matches := re.FindStringSubmatch(display)
		if len(matches) != 2 {
			return 0
		}
		offset := matches[1] // e.g. +05:30 or -08:00
		sign := 1
		if offset[0] == '-' {
			sign = -1
		}
		parts := strings.Split(offset[1:], ":")
		if len(parts) != 2 {
			return 0
		}
		hours, err1 := strconv.Atoi(parts[0])
		minutes, err2 := strconv.Atoi(parts[1])
		if err1 != nil || err2 != nil {
			return 0
		}
		return sign * (hours*60 + minutes)
	}

	// Sort entries: first by offset, then by display name, then by territory
	sort.SliceStable(entries, func(i, j int) bool {
		oi := parseOffset(entries[i].Display)
		oj := parseOffset(entries[j].Display)
		if oi != oj {
			return oi < oj // lower (more negative) comes first
		}
		if entries[i].Display != entries[j].Display {
			return entries[i].Display < entries[j].Display
		}
		return entries[i].Territory < entries[j].Territory
	})

	return entries
}

// generateSupportedTZIDs creates a slice of unique IANA timezone identifiers,
// sorted alphabetically by IANA timezone name.
func generateSupportedTZIDs(entries []Entry) []SupportedTZID {
	// Use a map to ensure uniqueness
	uniqueTZIDs := make(map[string]bool)

	for _, entry := range entries {
		uniqueTZIDs[entry.IANA] = true
	}

	// Convert to slice and sort alphabetically
	var supportedTZIDs []SupportedTZID
	for iana := range uniqueTZIDs {
		supportedTZIDs = append(supportedTZIDs, SupportedTZID{
			IANA: iana,
		})
	}

	sort.Slice(supportedTZIDs, func(i, j int) bool {
		return supportedTZIDs[i].IANA < supportedTZIDs[j].IANA
	})

	return supportedTZIDs
}

// generateGoFile generates the data_gen.go file containing the timezone mapping data and supported IANA timezones.
func generateGoFile(entries []Entry) error {
	supportedTZIDs := generateSupportedTZIDs(entries)

	templateData := struct {
		Entries        []Entry
		SupportedTZIDs []SupportedTZID
	}{
		Entries:        entries,
		SupportedTZIDs: supportedTZIDs,
	}

	tmpl, err := template.New("gofile").Parse(fileTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		return err
	}

	// Format the generated code using go/format
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(goFile, formatted, 0644)
}

// generateJSONFile generates the data_gen.json file containing the timezone mapping data in JSON format.
func generateJSONFile(entries []Entry) error {
	// Marshal to JSON with pretty formatting
	jsonData, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(jsonFile, jsonData, 0644)
}
