package main

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

const (
	cldrURL  = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml"
	xmlFile  = "references/windowsZones.xml"
	goFile   = "data_gen.go"
	jsonFile = "data_gen.json"
)

type SupplementalData struct {
	XMLName      xml.Name     `xml:"supplementalData"`
	WindowsZones WindowsZones `xml:"windowsZones"`
}

type WindowsZones struct {
	MapTimezones MapTimezones `xml:"mapTimezones"`
}

type MapTimezones struct {
	MapZone []MapZone `xml:"mapZone"`
}

type MapZone struct {
	Other     string `xml:"other,attr"`
	Territory string `xml:"territory,attr"`
	Type      string `xml:"type,attr"`
	Comment   string `xml:",comment"`
}

type XMLNode struct {
	XMLName  xml.Name
	Content  string    `xml:",chardata"`
	Comment  string    `xml:",comment"`
	Children []XMLNode `xml:",any"`
}

type Entry struct {
	Alias     string `json:"microsoftAlias"`
	Display   string `json:"microsoftDisplayName"`
	Territory string `json:"territory"`
	IANA      string `json:"iana"`
}

const fileTemplate = `// This file is automatically generated by the generator
// DO NOT EDIT MANUALLY
package winianatz

var data = []Entry{
{{range .Entries}}	{MicrosoftAlias: "{{.Alias}}", MicrosoftDisplayName: "{{.Display}}", Territory: "{{.Territory}}", IANA: "{{.IANA}}"},
{{end}}}
`

func main() {
	log.Println("Downloading windowsZones.xml from CLDR...")
	if err := downloadFile(cldrURL, xmlFile); err != nil {
		log.Fatalf("Failed to download XML: %v", err)
	}

	log.Println("Parsing XML...")
	entries, err := parseXML(xmlFile)
	if err != nil {
		log.Fatalf("Failed to parse XML: %v", err)
	}

	log.Println("Processing and sorting data...")
	sortedEntries := processAndSortEntries(entries)

	log.Println("Generating data_gen.go...")
	if err := generateGoFile(sortedEntries); err != nil {
		log.Fatalf("Failed to generate Go file: %v", err)
	}

	log.Println("Generating data_gen.json...")
	if err := generateJSONFile(sortedEntries); err != nil {
		log.Fatalf("Failed to generate JSON file: %v", err)
	}

	log.Println("Successfully generated data_gen.go and data_gen.json")
}

func downloadFile(url, filepath string) error {
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	out, err := os.Create(filepath)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, resp.Body)
	return err
}

func parseXML(filepath string) ([]Entry, error) {
	data, err := os.ReadFile(filepath)
	if err != nil {
		return nil, err
	}

	var entries []Entry
	decoder := xml.NewDecoder(bytes.NewReader(data))
	var currentComment string

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}

		switch t := token.(type) {
		case xml.Comment:
			comment := strings.TrimSpace(string(t))
			if strings.HasPrefix(comment, "(UTC") {
				currentComment = comment
			}
		case xml.StartElement:
			if t.Name.Local == "mapZone" {
				var mapZone MapZone
				if err := decoder.DecodeElement(&mapZone, &t); err != nil {
					return nil, err
				}

				// Process all territory entries with the current comment
				if currentComment != "" {
					// Handle multiple IANA zones separated by spaces
					ianaZones := strings.Fields(mapZone.Type)

					// Create an entry for each IANA zone
					for _, ianaZone := range ianaZones {
						entry := Entry{
							Alias:     mapZone.Other,
							Display:   currentComment,
							IANA:      ianaZone,
							Territory: mapZone.Territory,
						}
						entries = append(entries, entry)
					}
				}
			}
		}
	}

	return entries, nil
}

func processAndSortEntries(entries []Entry) []Entry {
	// Helper to extract offset as minutes from display string using regexp
	re := regexp.MustCompile(`\(UTC([+-]\d{2}:\d{2})\)`)
	parseOffset := func(display string) int {
		// Handle exactly "(UTC) ..." as offset 0
		if strings.HasPrefix(display, "(UTC)") {
			return 0
		}
		matches := re.FindStringSubmatch(display)
		if len(matches) != 2 {
			return 0
		}
		offset := matches[1] // e.g. +05:30 or -08:00
		sign := 1
		if offset[0] == '-' {
			sign = -1
		}
		parts := strings.Split(offset[1:], ":")
		if len(parts) != 2 {
			return 0
		}
		hours, err1 := strconv.Atoi(parts[0])
		minutes, err2 := strconv.Atoi(parts[1])
		if err1 != nil || err2 != nil {
			return 0
		}
		return sign * (hours*60 + minutes)
	}

	// Sort entries: first by offset, then by display name, then by territory
	sort.SliceStable(entries, func(i, j int) bool {
		oi := parseOffset(entries[i].Display)
		oj := parseOffset(entries[j].Display)
		if oi != oj {
			return oi < oj // lower (more negative) comes first
		}
		if entries[i].Display != entries[j].Display {
			return entries[i].Display < entries[j].Display
		}
		return entries[i].Territory < entries[j].Territory
	})

	return entries
}

func generateGoFile(entries []Entry) error {
	templateData := struct {
		Entries []Entry
	}{
		Entries: entries,
	}

	tmpl, err := template.New("gofile").Parse(fileTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData); err != nil {
		return err
	}

	// Format the generated code using go/format
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(goFile, formatted, 0644)
}

func generateJSONFile(entries []Entry) error {
	// Marshal to JSON with pretty formatting
	jsonData, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(jsonFile, jsonData, 0644)
}
